# Generated by Django 2.2 on 2020-06-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address', models.TextField(max_length=400, verbose_name='Address')),
                ('Shop Image', models.ImageField(upload_to='', verbose_name='Shop Image')),
                ('belongs_to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_info.CategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='product_info.Product')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_info.Shop')),
            ],
        ),
    ]
