# Generated by Django 2.2 on 2020-06-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_product',
            name='name',
            field=models.CharField(default='list', max_length=150, verbose_name='Name'),
        ),
    ]
