# Generated by Django 2.2 on 2020-06-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_info', '0002_shop_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Shop Image',
            new_name='image',
        ),
    ]
