# Generated by Django 2.2 on 2020-06-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('Groceries', 'Groceries'), ('Pharmacy', 'Pharmacy'), ('Music', 'Music'), ('Pets', 'Pets'), ('Sports', 'Sports'), ('Flowers', 'Flowers'), ('Stationery', 'Stationery'), ('Books', 'Books'), ('Scientific Equipments', 'Scientific Equipments'), ('Health', 'Health'), ('Fashion', 'Fashion'), ('Travel', 'Travel')], max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Product Image')),
                ('expiry', models.CharField(default='NA', max_length=100, verbose_name='Expiry (in months)')),
                ('quantity', models.CharField(default='NA', max_length=50, null=True, verbose_name='Quantity')),
            ],
        ),
    ]
